vocab = [
    ("bám rễ, ăn sâu vào", "take root in"),
    ("bối cảnh, cục diện", "landscape"),
    ("khái niệm, ý tưởng", "concept"),
    ("bẩm sinh, tự nhiên có", "innate"),
    ("thay thế, phế bỏ", "supplant"),
    ("năng lực nhận thức", "cognitive capability"),
    ("định lượng, đo lường", "quantify"),
    ("tìm kiếm, theo đuổi", "seek"),
    ("nhà tư tưởng tiến bộ", "progressive thinker"),
    ("nổi dậy, chống lại", "revolt"),
    ("quan niệm, ý niệm", "notion"),
    ("vốn có, bản chất", "inherent"),
    ("định mệnh, số phận", "destiny"),
    ("nhà giáo dục", "educator"),
    ("tư duy phát triển", "growth mindset"),
    ("học thuyết, lý thuyết", "theory"),
    ("hành lang", "hallway"),
    ("tạo động lực", "motivational"),
    ("bài phát biểu", "speech"),
    ("đường tới thành công đỉnh cao", "way to the top"),
    ("trọng tâm chính", "major focus"),
    ("dỗ dành, thuyết phục nhẹ nhàng", "coax"),
    ("lưu ý, ghi nhận", "note"),
    ("lời khen, khen ngợi", "praise"),
]
print("Vocabulary list created with", len(vocab), "entries.")
